## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: "\u2049 FAQ"
    url: "https://dayschedule.com/docs/"
    about: "Make sure you have read the Frequently Asked Questions page."
  - name: "\u2049 FAQ"
    url: "https://dayschedule.com/videos"
    about: "Watch video tutorials for general questions."
  - name: "\u2753 API Documentations"
    url: "https://dayschedule.com/docs/api"
    about: "Check API docuementaion with Postman collection to try the API."
